#!/usr/bin/env bash

enable_extension "appliance-image"

function extension_prepare_config__400_quark_image_defaults() {
	: "${QUARK_IMAGE_ENABLE_SSH:=no}"
	: "${QUARK_IMAGE_LOGIN_PASSWORD:=}"
	: "${QUARK_IMAGE_LOGIN_USER:=quark}"
	: "${QUARK_IMAGE_HOSTNAME:=quark}"
	: "${QUARK_IMAGE_PORT:=80}"
	: "${QUARK_IMAGE_BINARY_URL:=https://github.com/autobutler-org/quark/releases/latest/download/quark_Linux_arm64.tar.gz}"

	declare -g APPLIANCE_IMAGE_SERVICE_NAME="quark"
	declare -g APPLIANCE_IMAGE_SERVICE_DESCRIPTION="Quark Service"
	declare -g APPLIANCE_IMAGE_HOSTNAME="${QUARK_IMAGE_HOSTNAME}"
	declare -g APPLIANCE_IMAGE_SERVICE_USER="quark"
	declare -g APPLIANCE_IMAGE_SERVICE_GROUP="quark"
	declare -g APPLIANCE_IMAGE_LOGIN_USER="${QUARK_IMAGE_LOGIN_USER}"
	declare -g APPLIANCE_IMAGE_LOGIN_PASSWORD="${QUARK_IMAGE_LOGIN_PASSWORD}"
	declare -g APPLIANCE_IMAGE_CREATE_LOGIN_USER="yes"
	declare -g APPLIANCE_IMAGE_BINARY_URL="${QUARK_IMAGE_BINARY_URL}"
	declare -g APPLIANCE_IMAGE_BINARY_URL_EXTRACT_MODE="targz"
	declare -g APPLIANCE_IMAGE_BINARY_ARCHIVE_MEMBER="quark"
	declare -g APPLIANCE_IMAGE_BINARY_INSTALL_PATH="/usr/local/bin/quark"
	declare -g APPLIANCE_IMAGE_EXEC_START="/usr/local/bin/quark serve"
	declare -g APPLIANCE_IMAGE_WORKING_DIR="/var/lib/quark"
	declare -g APPLIANCE_IMAGE_DATA_DIR="/var/lib/quark/data"
	declare -g APPLIANCE_IMAGE_EXTRA_DIRECTORIES="/var/lib/quark/mounts"
	declare -g APPLIANCE_IMAGE_PACKAGES="avahi-daemon ufw udisks2"
	declare -g APPLIANCE_IMAGE_SYSTEMD_ENVIRONMENT="PORT=${QUARK_IMAGE_PORT} GIN_MODE=release"
	declare -g APPLIANCE_IMAGE_SYSTEMD_STANDARD_OUTPUT="append:/var/log/quark.app"
	declare -g APPLIANCE_IMAGE_SYSTEMD_STANDARD_ERROR="append:/var/log/quark.err"
	declare -g APPLIANCE_IMAGE_SYSTEMD_CAPABILITIES="CAP_NET_BIND_SERVICE"
	declare -g APPLIANCE_IMAGE_AVAHI_SERVICE_NAME="Quark on %h"
	declare -g APPLIANCE_IMAGE_AVAHI_SERVICE_PORT="${QUARK_IMAGE_PORT}"
	declare -g APPLIANCE_IMAGE_OPEN_PORTS="${QUARK_IMAGE_PORT}/tcp"
	declare -g APPLIANCE_IMAGE_ENABLE_SSH="${QUARK_IMAGE_ENABLE_SSH}"
	declare -g APPLIANCE_IMAGE_SUDOERS_FILENAME="quark"
	declare -g APPLIANCE_IMAGE_SUDOERS_CONTENT="quark ALL=(root) NOPASSWD: /bin/mount * /var/lib/quark/mounts/*, /bin/umount /var/lib/quark/mounts/*"
}
